### ISSUE TITLE
Changing Content-Type of the image to be viewable, not forced to download

### ISSUE THREAD

**Issue by spsaucier-bakkt** [leerob/nextjs-aws-s3#1]
What's the best way to make sure that the image uploaded to S3 is set to have a `Content-Type` of its image extension?

At the moment, this will upload as `binary/octet-stream`, so browsers will not be able to display the image but will try to download instead.

**Comment by leerob** [comment]
That content type is necessary to make this approach work as far as I know (pre-signed URL).

Check this out -> https://github.com/ryanto/next-s3-upload

**Comment by spsaucier-bakkt** [comment]
Actually, I figured it out -- you have to add `Content-Type` to `formData` _before_ you add the image to `formData`:
```ts
      formData.append("Content-Type", files[0].type);
      Object.entries({ ...fields, file: files[0] }).forEach(([key, value]) => {
        formData.append(key, value as Blob);
      });
```
